#pragma once

#include <cassert>
#include <cmath>
#include <stdexcept>
#include <vector>

#include "credit/daycount.hpp"
#include "credit/interp.hpp"

namespace credit {

// Discount curve bootstrapped from par yields (annual-pay bonds).
//
// Template parameters are policy classes (V2):
//   Interp — how to interpolate between knot DFs (e.g., LogLinearDF)
//   DC     — day-count convention for year fractions (e.g., Act365F)
template <typename Interp = LogLinearDF, typename DC = Act365F>
class DiscountCurve {
public:
    // Bootstrap from par yield term structure.
    //   tenors:     maturities in years (sorted ascending, e.g., {1,2,3,5,7,10,20,30})
    //   par_yields: par coupon rates in decimal (e.g., 0.0417 for 4.17%)
    //
    // Supports non-integer tenors: coupon dates are generated by stepping
    // backward from maturity in 1-year increments, producing a front stub
    // if the tenor is not an integer.  Each coupon is scaled by its accrual
    // fraction (the year-fraction between adjacent coupon dates).
    static DiscountCurve bootstrap(const std::vector<double>& tenors,
                                   const std::vector<double>& par_yields) {
        assert(tenors.size() == par_yields.size());
        assert(!tenors.empty());

        std::vector<double> knot_tenors;
        std::vector<double> knot_dfs;

        knot_tenors.push_back(0.0);
        knot_dfs.push_back(1.0);

        for (std::size_t k = 0; k < tenors.size(); ++k) {
            double T = tenors[k];
            double c = par_yields[k];

            // --- Build coupon schedule ---
            // Step backward from T by 1.0; first period may be a stub.
            std::vector<double> cpn_dates;
            for (double t = T; t > 1e-12; t -= 1.0) {
                cpn_dates.push_back(t);
            }
            // cpn_dates is in descending order; reverse to ascending
            std::reverse(cpn_dates.begin(), cpn_dates.end());

            // Compute accrual fractions for each coupon period
            std::vector<double> accruals(cpn_dates.size());
            accruals[0] = cpn_dates[0];  // stub or 1.0
            for (std::size_t i = 1; i < cpn_dates.size(); ++i) {
                accruals[i] = cpn_dates[i] - cpn_dates[i - 1];
            }

            // --- Separate known vs. dependent coupon dates ---
            double t_prev = knot_tenors.back();
            double df_prev = knot_dfs.back();
            double known_pv = 0.0;

            // Collect dependent coupon info: (alpha, accrual) pairs
            struct DepCoupon { double alpha; double accrual; };
            std::vector<DepCoupon> dep_coupons;
            double mat_accrual = 0.0;
            bool maturity_is_coupon = false;

            for (std::size_t j = 0; j < cpn_dates.size(); ++j) {
                double t_j = cpn_dates[j];
                double acc = accruals[j];

                if (t_j <= t_prev + 1e-12) {
                    // Known: DF(t_j) already determined
                    known_pv += c * acc * Interp::interp(knot_tenors, knot_dfs, t_j);
                } else if (std::abs(t_j - T) < 1e-12) {
                    // Maturity coupon: coefficient depends on x directly
                    maturity_is_coupon = true;
                    mat_accrual = acc;
                } else {
                    // Dependent: DF(t_j) = df_prev^(1-alpha) * x^alpha
                    double alpha = (t_j - t_prev) / (T - t_prev);
                    dep_coupons.push_back({alpha, acc});
                }
            }

            // --- Newton's method: solve for x = DF(T) ---
            // f(x) = known_pv + sum_j(c * acc_j * df_prev^(1-a_j) * x^a_j)
            //       + (1 + c * mat_acc) * x - 1    [if maturity is coupon]
            //       + x - 1                         [otherwise]

            double x = df_prev * std::exp(-c * (T - t_prev));  // initial guess

            constexpr int kMaxIter = 50;
            constexpr double kTol = 1e-14;
            bool converged = false;

            for (int iter = 0; iter < kMaxIter; ++iter) {
                double dep_pv = 0.0;
                double dep_deriv = 0.0;

                for (const auto& dc : dep_coupons) {
                    double xa = std::pow(x, dc.alpha);
                    double dp = std::pow(df_prev, 1.0 - dc.alpha);
                    dep_pv += c * dc.accrual * dp * xa;
                    dep_deriv += c * dc.accrual * dp * dc.alpha * xa / x;
                }

                double mat_coeff = maturity_is_coupon ? (1.0 + c * mat_accrual) : 1.0;
                double f = known_pv + dep_pv + mat_coeff * x - 1.0;
                double fp = dep_deriv + mat_coeff;

                double dx = -f / fp;
                x += dx;

                if (std::abs(dx) < kTol) {
                    converged = true;
                    break;
                }
            }

            if (!converged) {
                throw std::runtime_error(
                    "bootstrap: Newton failed to converge at tenor "
                    + std::to_string(T));
            }

            if (x <= 0.0 || x > 1.0) {
                throw std::runtime_error(
                    "bootstrap: invalid discount factor at tenor "
                    + std::to_string(T));
            }

            knot_tenors.push_back(T);
            knot_dfs.push_back(x);
        }

        DiscountCurve curve(std::move(knot_tenors), std::move(knot_dfs));
        curve.input_tenors_ = tenors;
        curve.input_par_yields_ = par_yields;
        return curve;
    }

    // Discount factor at time t (in years).
    [[nodiscard]] double df(double t) const {
        if (t <= 0.0) { return 1.0; }
        return Interp::interp(tenors_, dfs_, t);
    }

    // Discount factor with a parallel additive shift to the zero rate.
    //   DF_shifted(t) = DF(t) * exp(-spread * t)
    [[nodiscard]] double df_with_zspread(double t, double spread) const {
        if (t <= 0.0) { return 1.0; }
        return df(t) * std::exp(-spread * t);
    }

    // Continuously-compounded zero rate at time t.
    [[nodiscard]] double zero_rate(double t) const {
        if (t <= 0.0) { return 0.0; }
        return -std::log(df(t)) / t;
    }

    // Re-bootstrap with all par yields shifted by a parallel amount.
    [[nodiscard]] DiscountCurve parallel_shift(double shift) const {
        assert(!input_tenors_.empty());
        std::vector<double> shifted(input_par_yields_.size());
        for (std::size_t i = 0; i < shifted.size(); ++i) {
            shifted[i] = input_par_yields_[i] + shift;
        }
        return bootstrap(input_tenors_, shifted);
    }

    // Re-bootstrap with a single tenor's par yield shifted.
    [[nodiscard]] DiscountCurve key_rate_shift(std::size_t idx, double shift) const {
        assert(idx < input_par_yields_.size());
        auto shifted = input_par_yields_;
        shifted[idx] += shift;
        return bootstrap(input_tenors_, shifted);
    }

    [[nodiscard]] const std::vector<double>& tenors() const { return tenors_; }
    [[nodiscard]] const std::vector<double>& dfs() const { return dfs_; }
    [[nodiscard]] const std::vector<double>& input_tenors() const { return input_tenors_; }
    [[nodiscard]] const std::vector<double>& input_par_yields() const { return input_par_yields_; }
    [[nodiscard]] std::size_t size() const { return tenors_.size(); }
    [[nodiscard]] std::size_t num_tenors() const { return input_tenors_.size(); }

private:
    DiscountCurve(std::vector<double> tenors, std::vector<double> dfs)
        : tenors_(std::move(tenors)), dfs_(std::move(dfs)) {}

    std::vector<double> tenors_;
    std::vector<double> dfs_;
    std::vector<double> input_tenors_;      // original bootstrap inputs
    std::vector<double> input_par_yields_;  // original bootstrap inputs
};

}  // namespace credit
